#!/usr/bin/env perl

use v5.34;

use FindBin qw($Bin);
use lib "$Bin/../lib";

use BBSConnectionGateway;

sub main {
    my $custom_config = $ARGV[0] // "";
    my $filter = BBSConnectionGateway->new(config => $custom_config);
    $filter->run;

    return 0;
}

exit(main);
